config/routes.rb
Rails.application.routes.draw do
  root to: 'parkings#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    ulocks: 'usres/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :parkings, only: [:index]

  resources :bookings, only: [:index, :new, :create, :destroy] do
    member do
      get :confirm_destroy
      get :confirm_release
      get :release
    end
  end

  post "/slack/command", to: "slack/commands#create"
end

app/models/booking.rb
class Booking < ApplicationRecord
    after_commit :set_end_date, :book_spot, on: :create

    belongs_to :spot
    belongs_to :user

    attr_accessor :timezone

    validates :start_date, :car_name, :car_plates, presence: true

    enum status: {
        archive: 0,
        active: 1
    }

    scope :by_create_date, ->{ order(created_at: :desc) }
    scope :by_status, lambda { |status|
        where(status: status) if status.present?
    }

    def archive
        update({status: :archive})
        spot.release
    end

    def car_details
        "#{car_name}, #{car_plates}"
    end

    private

    def set_end_date
        update(end_date: start_date.to_date.in_time_zone(timezone).end_of_day)
    end

    def book_spot
        spot.book
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings.by_status(params[:status]).by_create_date
  end

  def new
    render partial: 'new', layout: 'modal', locals: {
      booking: Booking.new,
      parking: Parking.find(params[:parking_id])
    }
  end

  def create
    booking = Booking.new(booking_params)
    booking.user = current_user
    booking.status = :active

    if booking.save
      ReleaseBookingJob.set(wait_until: booking.end_date).perform_later(booking)
      redirect_to bookings_url
    else
      render json: { errors: booking.errors }, status: :unprocessable_entity
    end
  end

  def confirm_destroy
    booking = Booking.find(params[:id])
    render partial: 'confirm_destroy', layout: 'modal', locals: { id: booking.id }
  end

  def destroy
    booking = Booking.find(params[:id])
    if booking.delete
      booking.spot.release
      redirect_to bookings_url
    end
  end

  def confirm_release
    booking = Booking.find(params[:id])
    render partial: 'confirm_release', layout: 'modal', locals: { id: booking.id }
  end

  def release
    booking = Booking.find(params[:id])
    booking.archive
    redirect_to bookings_url
  end

  private

  def booking_params
    params.fetch(:booking, {}).permit(:spot_id, :start_date, :car_name, :car_plates, :timezone)
  end
end

app/views/bookings/_confirm_destroy.html.erb
<%= content_for :modal_title, 'Confirm deletion' %>
<h5 class="text-gray-900 font-bold text-2xl tracking-tight mb-2">Are you sure?</h5>
<footer class="modal__footer">
    <div class="form__group form__group--inline">
        <button class="link w-full modal__close" data-action="click->modal#close">Cancel</button>
        <%= link_to 'Yes, delete', booking_url(id), class: "button button--block button--red", method: :delete %>
    </div>
</footer>

app/views/bookings/_confirm_release.html.erb
<%= content_for :modal_title, 'Confirm release' %>
<h5 class="text-gray-900 font-bold text-2xl tracking-tight mb-2">Are you sure?</h5>
<footer class="modal__footer">
    <div class="form__group form__group--inline">
        <button class="link w-full modal__close" data-action="click->modal#close">Cancel</button>
        <%= link_to 'Yes, release', release_booking_url(id), class: "button button--block button--green" %>
    </div>
</footer>

app/views/bookings/_form.html.erb
<%= form_with model: booking, id: :parkings_booking, class: "form w-full", data: { controller: "form", form_id: :booking, form_target: "form", action: "ajax:beforeSend->form#onSubmit ajax:error->form#onError" }, local: false do |f| %>
    <%= f.hidden_field :timezone, data: { form_target: 'timezone' } %>

    <div class="form__group form__group--inline">
        <div class="w-full">
            <%= f.label :spot, "Select spot number", class: "form__label" %>
            <div data-controller="select">
                <%= f.select :spot_id, options_for_select(parking.spots.availables.collect {|s| [s.id, s.id]}, booking.spot), {}, { class: "js-select", data: { select_target: "select", classes: "select select--block form__input" } } %>
            </div>
        </div>

        <div class="w-full">
            <%= f.label :start_date, "When to start?", class: "form__label" %>
            <%= f.datetime_field :start_date, class: "form__input", min: Date.today %>
        </div>
    </div>

    <div class="form__group form__group--inline">
        <div class="w-full">
            <%= f.label :car_name, class: "form__label" %>
            <%= f.text_field :car_name, class: "form__input" %>
        </div>

        <div class="w-full">
            <%= f.label :car_plates, class: "form__label" %>
            <%= f.text_field :car_plates, class: "form__input" %>
        </div>
    </div>

    <footer class="modal__footer">
        <div class="form__group form__group--inline">
            <button class="link w-full modal__close" data-action="click->modal#close">Cancel</button>
            <%= f.button "Book", class: "button button--block button--blue", data: { form_target: "button" } %>
        </div>
    </footer>
<% end %>

app/views/bookings/_new.html.erb
<%= content_for :modal_title, 'Book the place' %>

<h5 class="text-gray-900 font-bold text-2xl tracking-tight mb-2"><%= parking.company.name %></h5>
<small class="text-gray-400">Parking address</small><br>
<p class="font-normal text-gray-700 mb-6"><%= parking.address %></p>

<%= render partial: 'form', locals: { booking: booking, parking: parking } %>

app/views/bookings/index.html.erb
<%= render partial: 'shared/heading', locals: { title: 'Booked Spots', subtitle: 'Checklist of your bookings' } %>

<ul class="section-nav">
    <li class="section-nav__item">
        <%= link_to "All", bookings_url, class: "link #{"link--blue" unless params[:status]}" %>
    </li>
    <li class="section-nav__item">
        <%= link_to "Current", bookings_url(status: :active), class: "link #{"link--blue" if params[:status] === :active.to_s}" %>
    </li>
    <li class="section-nav__item">
        <%= link_to "History", bookings_url(status: :archive), class: "link #{"link--blue" if params[:status] === :archive.to_s}" %>
    </li>
</ul>

<%= render partial: "shared/no_records", locals: { title: 'Sorry.', content: 'No records found on this query.' } unless @bookings.present? %>

<div class="cards">
    <% @bookings.each do |booking| %>
        <article class="card">
            <div class="card__section">
                <a href="#" class="text-2xl font-bold text-gray-700 hover:text-gray-600 hover:underline"><%= booking.spot.parking.company.name %></a>
                <p class="mt-1 text-gray-600">
                    <small class="text-gray-400">Parking address</small><br>
                    <%= booking.spot.parking.address %>
                </p>
            </div>

            <div class="card__section">
                <p class="mt-1 text-gray-600">
                    <small class="text-gray-400">Started at</small><br>
                    <small><%= I18n.l(booking.start_date, format: :long) %></small>
                </p>
            </div>

            <div class="card__section">
                <div class="mt-1 text-gray-600">
                    <small class="text-gray-400">Place number</small><br>
                    <small><%= booking.spot.id %></small>
                </div>

                <div class="mt-1">
                    <small class="mt-1 text-gray-600">
                        <span class="text-gray-400">Car details</span><br>
                        <%= booking.car_details %>
                    </small>
                </div>
            </div>

            <div class="card__actions card__actions--inline">
                <div data-controller="modal" data-modal-target="modal" data-modal-url="<%= confirm_destroy_booking_url(booking) %>">
                    <%= button_tag "Delete", class: "button button--block button--red", data: { modal_target: "button", action: "click->modal#open" } %>
                </div>
                <div data-controller="modal" data-modal-target="modal" data-modal-url="<%= confirm_release_booking_url(booking) %>">
                    <%= button_tag "Release now", class: "button button--block button--#{booking.archive? ? "gray button--disabled" : "green"}", data: { modal_target: "button", action: "click->modal#open" }, disabled: booking.archive? %>
                </div>
            </div>
        </article>
    <% end %>
</div>