config/routes.rb
Rails.application.routes.draw do
  root to: 'parkings#index'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    ulocks: 'usres/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :parkings, only: [:index]

  resources :bookings, only: [:index, :new, :create, :destroy] do
    member do
      get :confirm_destroy
      get :confirm_release
      get :release
    end
  end

  post "/slack/command", to: "slack/commands#create"
end

app/views/layouts/_modal.html.erb
<div id="modal-background" class="modal__background fixed top-0 left-0 w-full h-full animated faster fade-in" data-modal-target="background" style="background: rgba(100, 100, 100, 0.6); z-index: 9998;">
    <div class="modal" data-modal-target="container" data-action="mousedown->modal#close keyup@window->modal#closeByEsc">
        <div class="modal__wrapper" data-modal-target="wrapper">
            <div class="modal__header">
                <h2 class="modal__title"><%= content_for :modal_title %></h2>
                <button class="modal__close" data-action="click->modal#close">
                    <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
                    </svg>
                </button>
            </div>
            <div class="modal__content">
                <%= yield %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-screen bg-gray-100 antialiased">
    <header class="header">
      <div class="mx-auto">
        <h1 class="text-3xl font-bold text-gray-600 md:text-5xl"><%= current_user.name %></h1>
        <p class="text-gray-500"><%= current_user.email %></p>
      </div>

      <nav class="nav">
        <div class="flex items-center justify-center p-3 mx-auto text-gray-600">
          <%= link_to "parkings", parkings_url, class: "nav__item #{"nav__item--current" if controller_name === 'parkings'}" %>
          <%= link_to "bookings", bookings_url, class: "nav__item #{"nav__item--current" if controller_name === 'bookings'}" %>
          <div data-controller="modal" data-modal-target="modal" data-modal-url="<%= edit_user_registration_url %>" data-modal-spinner="false">
            <%= button_tag "settings", class: "nav__item", data: { modal_target: "button", action: "click->modal#open" } %>
          </div>
          <%= button_to "logout", destroy_user_session_url, class: "nav__item", method: :delete if current_user %>
        </div>
      </nav>
    </header>

    <main class="main">
      <%= yield %>
    </main>

    <div class="flex flex-wrap items-center md:justify-between justify-center">
      <div class="container px-4 mx-auto text-center">
        <div class="text-sm text-gray-400 py-6">
          Copyright © <span id="get-current-year"><%= Date.today.year %></span> Wojciech Dabrovski
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-screen bg-gray-100 antialiased">
    <%= yield %>
  </body>
</html>